sudo: false
language: node_js
node_js:
- '6'
- '5'
- '4'
- '0.12'
deploy:
  provider: gae
  keyfile: client.json.enc
  project: runshawbusalerts
  skip_cleanup: true
before_install:
- openssl aes-256-cbc -K $encrypted_1cd687514378_key -iv $encrypted_1cd687514378_iv
  -in client-secret.json.enc -out client-secret.json -d
