language: node_js
node_js:
  - 6
  - 8

branches:
  only:
    - master

before_script:
  - cd alerts
  - npm install -g vue-cli
  - npm install

script:
  - npm run build --report

notifications:
  email:
    on_failure: change
    on_success: change