sudo: false
language: node_js
node_js:
- '6'
- '5'
- '4'
- '0.12'
before_install:
- openssl aes-256-cbc -K $encrypted_d4cb17e9e0a9_key -iv $encrypted_d4cb17e9e0a9_iv
  -in client.json.enc -out .\\client.json -d
deploy:
  provider: gae
  keyfile: ./client.json.enc
  project: runshawbusalerts
  skip_cleanup: true